### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by pgupt** [viral-vector/vue-upload-image#10]
`vm.js:85 Uncaught C:\Users\<User>\eclipse-workspace\electron-desktop\node_modules\vue-upload-image\dist\upload_image.vue:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { <template>
                                                                                                                                                           ^

SyntaxError: Unexpected token <
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:766:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)`

I am getting this error. Can you help with what might be causing it?

Also, where do I copy configuration? I am new to Vue so I apologize if it is a silly question.

After some more investigation, I found that it is not recognizing <template> tag in the upload_image.vue itself.  I am using electron-vue rather than a simple Vue project.

**Comment by Patryk-Szylin** [comment]
Got the same error, This has a dependency on Bootstrap, which is a bit inconvenient for me

**Comment by viral-vector** [comment]
@pgupt this was not built with electron in mind. @Patryk-Szylin this package has no dependencies

**Comment by toshkoevo** [comment]
I get the same error on NuxtJS (Vue2)
